# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Server_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import socket
from PyQt5 import QtCore, QtGui, QtWidgets
import server



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 442)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QTextEdit(self.centralwidget)
        self.title.setEnabled(False)
        self.title.setGeometry(QtCore.QRect(-1, -1, 601, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setAccessibleName("")
        self.title.setAccessibleDescription("")
        self.title.setAutoFillBackground(False)
        self.title.setStyleSheet("background-color: rgb(0, 0, 255);\n"
        "color: rgb(255, 255, 0);")
        self.title.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.title.setReadOnly(True)
        self.title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title.setObjectName("title")
        self.beginButton = QtWidgets.QPushButton(self.centralwidget)
        self.beginButton.setGeometry(QtCore.QRect(170, 300, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.beginButton.setFont(font)
        self.beginButton.setObjectName("beginButton")
        self.ipLabel = QtWidgets.QLabel(self.centralwidget)
        self.ipLabel.setGeometry(QtCore.QRect(50, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ipLabel.setFont(font)
        self.ipLabel.setAutoFillBackground(False)
        self.ipLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ipLabel.setWordWrap(False)
        self.ipLabel.setObjectName("ipLabel")
        self.ipField = QtWidgets.QLineEdit(self.centralwidget)
        self.ipField.setGeometry(QtCore.QRect(150, 150, 301, 41))
        
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ipField.setFont(font)
        self.ipField.setStyleSheet("background-color: rgb(229, 231, 233);\n"
        "color: rgb(98, 101, 103);")
        self.ipField.setInputMask("")
        self.ipField.setText("")
        self.ipField.setDragEnabled(False)
        self.ipField.setReadOnly(True)
        self.ipField.setPlaceholderText("")
        self.ipField.setClearButtonEnabled(False)
        self.ipField.setObjectName("ipField")
        self.portField = QtWidgets.QLineEdit(self.centralwidget)
        self.portField.setGeometry(QtCore.QRect(150, 230, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.portField.setFont(font)
        self.portField.setInputMask("")
        self.portField.setText("")
        self.portField.setAlignment(QtCore.Qt.AlignCenter)
        self.portField.setDragEnabled(False)
        self.portField.setReadOnly(False)
        self.portField.setClearButtonEnabled(False)
        self.portField.setObjectName("portField")
        self.portLabel = QtWidgets.QLabel(self.centralwidget)
        self.portLabel.setGeometry(QtCore.QRect(10, 230, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.portLabel.setFont(font)
        self.portLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.portLabel.setObjectName("portLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">SERVIDOR</span></p></body></html>"))
        self.beginButton.setText(_translate("MainWindow", "Conectar"))
        self.ipLabel.setText(_translate("MainWindow", "IP:"))
        self.portField.setPlaceholderText(_translate("MainWindow", "INGRESE EL PUERTO"))
        self.portLabel.setText(_translate("MainWindow", "PORT:"))



def startServer():
    
    port = ui.portField.text()
    if(port==""):
        print("Ingrese valor de puerto")
    else:
        sv = server.Servidor(int(port))
        sv.startConnection()


if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setWindowTitle('Servidor')
    ui.ipField.setText(socket.gethostbyname(socket.gethostname()))
    ui.beginButton.clicked.connect(startServer)
    
    MainWindow.show()

    sys.exit(app.exec_())

